development:
  adapter: sqlite3
  database: db/personalblog_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/personalblog_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: personalblog_production
  username: <%= ENV['PERSONALBLOG_DATABASE_USERNAME'] %>
  password: <%= ENV['PERSONALBLOG_DATABASE_PASSWORD'] %>
  # url: <%= ENV['DATABASE_URL'] %>